"""gen_baseline_report.py — write tests/BASELINE_RESULTS.md from the locked golden + engine.

Summarizes the current-engine baseline that the test suite pins: 3-stack / 2-stack / vet
counts (from golden/INDEX.json), the physical-decider predictions (replayed live), the tri
reference counts, and the JS<->Py parity status. Re-run after any refactor and diff the file;
identical = fidelity preserved.

Usage:  python tests/gen_baseline_report.py
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
for _p in (HERE, os.path.join(ROOT, "py"), os.path.join(ROOT, "py", "tri")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import enginelib as EL  # noqa: E402

GOLDEN = os.path.join(HERE, "golden")
RESULTS = os.path.join(ROOT, "results")


def _load(path: str) -> object:
    """Load JSON or return None if absent. I/O: (path) -> parsed | None."""
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def _index() -> dict:
    """Golden INDEX.json (name -> summary), or {}. I/O: () -> dict."""
    return _load(os.path.join(GOLDEN, "INDEX.json")) or {}


def _vet_hash_map() -> dict[str, bool]:
    """Merge all vet_*.json golden into {normalized canonical hash -> engine foldable}.
    I/O: () -> dict."""
    merged: dict[str, bool] = {}
    if not os.path.isdir(GOLDEN):
        return merged
    for fn in os.listdir(GOLDEN):
        if fn.startswith("vet_"):
            for c in (_load(os.path.join(GOLDEN, fn)) or {}).get("candidates", []):
                merged[EL.norm_hash(c["hash"])] = c["foldable"]
    return merged


def _decider_rows() -> list[dict]:
    """Match each physical-labelled decider's canonical hash in the vet golden; compare to physics.
    I/O: () -> [{grid,id,physical,predicted,agree}] (predicted None if grid not yet vetted)."""
    labels = _load(os.path.join(RESULTS, "twoplus1_labels.json")) or []
    hmap = _vet_hash_map()
    rows: list[dict] = []
    for lab in labels:
        if lab.get("foldable") is None:
            continue
        physical = bool(lab["foldable"])
        h = EL.norm_hash(lab["canonicalHash"])
        predicted = bool(hmap[h]) if h in hmap else None
        rows.append({"grid": lab["grid"], "id": lab["id"], "physical": physical,
                     "predicted": predicted,
                     "agree": (predicted == physical) if predicted is not None else None})
    return rows


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a markdown table. I/O: (headers, rows of cells) -> md string."""
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def build() -> str:
    """Assemble the full BASELINE_RESULTS.md body. I/O: () -> md string."""
    idx = _index()
    lines: list[str] = []
    lines.append("# Baseline results — current-engine fidelity lock (Session 0)\n")
    lines.append("Generated by `tests/gen_baseline_report.py` from the committed golden files in "
                 "`tests/golden/` plus a live engine replay. This is the reference every later "
                 "session diffs against: after a refactor, regenerate and the tables must be "
                 "identical (or a change must be a documented, justified improvement).\n")

    # 3-stack
    three = sorted([v for v in idx.values() if v.get("kind") == "3stack"],
                   key=lambda v: (v["m"], v["n"], v["allowNonCorner"]))
    if three:
        lines.append("## 3-stack solutions (golden, re-run 1:1 by `test_golden.py`)\n")
        lines.append(_md_table(
            ["grid", "allowNonCorner", "solutions", "Tw=0", "byDecomp", "byShape"],
            [[f"{v['m']}x{v['n']}", v["allowNonCorner"], v["count"], v["twist0"],
              v.get("byDecomp", {}), v.get("byShape", {})] for v in three]))
        lines.append("\nCommitted-manifest cross-check (allowNonCorner=False): "
                     "6x4→2, 6x5→3, 6x6→12, 6x7→33, 9x4→19, 8x6→310, 12x4→90 — all reproduced.\n")

    # 2-stack
    two = sorted([v for v in idx.values() if v.get("kind") == "2stack"],
                 key=lambda v: (v["m"], v["n"]))
    if two:
        lines.append("## 2-stack RSPA (Hamiltonian-circuit) baseline\n")
        lines.append(_md_table(["grid", "HC patterns", "foldable"],
                                [[f"{v['m']}x{v['n']}", v["count"], v["foldable"]] for v in two]))
        lines.append("")

    # vet hard-case
    vet = sorted([v for v in idx.values() if v.get("kind") == "vet"],
                 key=lambda v: (v["m"], v["n"], v["allowNonCorner"]))
    if vet:
        lines.append("## Hard-case oracle — ALL closing candidates (FOLD + predicted-JAM)\n")
        lines.append("The strongest discriminator: every distinct (D4-deduped) closing fold, "
                     "including the rejects, tagged by the gate it fails.\n")
        lines.append(_md_table(["grid", "allowNonCorner", "closing", "FOLD", "JAM"],
                               [[f"{v['m']}x{v['n']}", v["allowNonCorner"], v["closing"],
                                 v["fold"], v["jam"]] for v in vet]))
        lines.append("")

    # physical deciders
    rows = _decider_rows()
    if rows:
        def _pred(r: dict) -> str:
            if r["predicted"] is None:
                return "pending (grid not vetted)"
            return "FOLD" if r["predicted"] else "JAM"

        def _agree(r: dict) -> str:
            if r["agree"] is None:
                return "—"
            return "✓" if r["agree"] else "✗ MISMATCH"

        lines.append("## Physical deciders — engine prediction vs recorded paper-fold\n")
        lines.append(_md_table(
            ["grid#id", "physical", "engine", "agree"],
            [[f"{r['grid']}#{r['id']}", "FOLD" if r["physical"] else "JAM",
              _pred(r), _agree(r)] for r in rows]))
        decided = [r for r in rows if r["agree"] is not None]
        nagree = sum(r["agree"] for r in decided)
        lines.append(f"\nAgreement: {nagree}/{len(decided)} matched deciders agree with physics "
                     f"({len(rows) - len(decided)} pending vet enumeration).\n")

    # tri reference
    tri_all = _load(os.path.join(RESULTS, "tri_K12_hl_all.json"))
    tri_fold = _load(os.path.join(RESULTS, "tri_foldable_K12_hl.json"))
    if isinstance(tri_all, list):
        nf = len(tri_fold) if isinstance(tri_fold, list) else "?"
        lines.append("## Triangle-lattice reference (45-45-90 tetrakis, K=12)\n")
        lines.append(f"- all closing folds: **{len(tri_all)}**\n- foldable subset: **{nf}**\n"
                     "- locked by `test_tri_reference.py` (side-matching disqualifies all "
                     "K=12 Tw=0; foldable subset is a strict subset of the all-set).\n")

    # parity
    lines.append("## JS ↔ Python engine parity\n")
    lines.append("`test_parity_js.py` runs both engines on 6x4, 6x5, 6x6 and compares normalized "
                 "canonical-hash sets. **Result: identical** (counts 2/3/12; zero JS-only or "
                 "Py-only hashes). Known gate drift (JS enforces mn%6, K-even, n≥4; Python "
                 "relaxed to mn%3) does not surface on these grids; it is catalogued for the "
                 "Session-3 engine-rules spec.\n")

    # known gaps (from the Session-0 adversarial review)
    lines.append("## Known gaps (adversarial review, Session 0)\n")
    lines.append("- **One-sided physical ground truth.** All labelled deciders are JAM, so the "
                 "decider tests can catch the engine wrongly predicting FOLD on a real jam, but "
                 "NOT wrongly predicting JAM on a real foldable. Need at least one physically-"
                 "confirmed FOLD decider per grid (e.g. the 6x6 edge fold noted in LAB_LOG) added "
                 "to `twoplus1_labels.json` to close this.\n")
    lines.append("- **Heavy grids not committed as golden.** 8x6 (310) and 12x4 (90) are locked "
                 "only by `test_manifest_counts.py` (slow tier), not by a committed golden — run "
                 "`gen_golden.py heavy` to add them.\n")
    lines.append("- **Canonical hash ≠ replayable path.** `transform_arrow` is not "
                 "replay-equivariant with `apply_transform`; the hash is a sound D4 dedup key "
                 "(verified: perfect bijection onto symmetry orbits, zero false merges/splits) but "
                 "must be matched, never replayed. Tracked for the Session-3 engine-rules spec.\n")
    return "\n".join(lines) + "\n"


def main() -> int:
    body = build()
    out = os.path.join(HERE, "BASELINE_RESULTS.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"wrote {os.path.relpath(out, ROOT)} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
