"""make_fold_bundle.py — park the exact 2+1 patterns to physically fold into one folder.

Pulls full solution records (footprint + chains + foldArrows + all 4 engine twist tags) from
`results/2+1 testing/all_2plus1.json` for the curated to-fold set, and writes a self-contained
bundle to `results/2+1 testing/to_fold/`:
  <grid>_<id>.json   one pattern per file (load in the frontend viewer, or read the arrows directly)
  _TEST_PLAN.md      what each fold decides + the FOLD-vs-JAM outcome table
  _manifest.json     machine index

Edit TO_FOLD below and rerun to re-park a different set:
  python experimental/make_fold_bundle.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "results", "2+1 testing", "all_2plus1.json")
OUTDIR = os.path.join(ROOT, "results", "2+1 testing", "to_fold")

# The minimal covering set (grid, id) -> why we fold it. Order = priority.
TO_FOLD = [
    ("8x6", 202, {
        "tier": "CRITICAL — twist gate decider",
        "class": "twisted (Tw=-720), the lone reflection+parity passer twist rejects across all 264",
        "predicted": "engine ADMITS it (passes exit+parity+reflection; shipped engine does not twist-gate 2+1)",
        "FOLD_means": "Tw=-720 is a FALSE-REJECT -> the twist criterion is wrong / needs work",
        "JAM_means": "reflection FALSE-PASSES a real jam -> the twist gate earns its keep (wire Model B in)",
    }),
    ("6x6", 19, {
        "tier": "control — first positive FOLD ground truth (every existing label is JAM)",
        "class": "flat (Rect), Tw=0 on every sound engine, partial=flat",
        "predicted": "FOLD (flat-folds onto the 3-cell footprint stack)",
        "FOLD_means": "gates correctly admit a real fold (closes the zero-FOLD-label gap)",
        "JAM_means": "a reflection+parity+twist passer still jams -> a gate is MISSING (high alarm)",
    }),
    ("6x6", 18, {
        "tier": "overhang hypothesis — intrinsic",
        "class": "intrinsic overhang (Rect, partial Tw=+1*Q atan-half residual; not hub-removable)",
        "predicted": "lead's hypothesis: closes with one end PROTRUDING a half-cell past the footprint",
        "FOLD_means": "overhang is a real (offset) fold -> partial decomp earns a place beside jump",
        "JAM_means": "the atan-half residual = a genuine jam -> partial decomp is just noise here",
    }),
    ("6x6", 5, {
        "tier": "overhang hypothesis — hub-removable",
        "class": "hub-removable overhang (L, partial Tw=+1*Q; overhang VANISHES when hubs forced 1-unit)",
        "predicted": "if the stick-out is only a fixable HUB seam, this should fold flatter than #18",
        "FOLD_means": "hub seam is the overhang source (fixable) -> distinguishes hub vs interior overhang",
        "JAM_means": "even the hub-removable case jams -> overhang is not a fold signature at all",
    }),
]


def _chain_lines(chains):
    out = []
    for c in chains:
        base = " ".join("(%d,%d)" % (b["x"], b["y"]) for b in c["baseCells"])
        out.append("    %-7s base %-18s arrows: %s"
                   % (c["kind"], base, " ".join(c["foldArrows"])))
    return out


def main():
    src = json.load(open(SRC))
    index = {(s["grid"], s["id"]): s for s in src["solutions"]}
    os.makedirs(OUTDIR, exist_ok=True)
    for stale in os.listdir(OUTDIR):
        os.remove(os.path.join(OUTDIR, stale))

    manifest, md = [], []
    md.append("# To-fold bundle — 2+1 patterns to physically test\n")
    md.append("Generated by `experimental/make_fold_bundle.py` from the verified engine tags "
              "(`results/2+1 testing/all_2plus1.json`). Each `<grid>_<id>.json` is a full pattern "
              "(footprint + both chains' base cells + fold-arrow order + every engine's twist verdict); "
              "load it in the frontend viewer or read the arrows below directly.\n")
    md.append("**Fold protocol:** lay the m×n sheet, cut the slits, fold each chain's creases in the "
              "listed arrow order (L/R/U/D = fold that edge over). FOLD = collapses flat to the 3-cell "
              "footprint stack; JAM = self-blocks. Record the result + any protruding strip.\n")
    md.append("## Outcome table\n")
    md.append("| # | pattern | K | shape | class | predict FOLD ⇒ | predict JAM ⇒ |")
    md.append("|---|---------|---|-------|-------|----------------|----------------|")

    for i, (grid, sid, meta) in enumerate(TO_FOLD, 1):
        s = index.get((grid, sid))
        if s is None:
            print("  MISSING %s#%d in source" % (grid, sid))
            continue
        m, n = map(int, grid.split("x"))
        K = m * n // 3
        shape = s["footprint"]["shape"]
        rec = {
            "grid": grid, "id": sid, "m": m, "n": n, "K": K,
            "test": meta,
            "footprint": s["footprint"],
            "decomposition": s["decomposition"],
            "chains": [{"kind": c["kind"], "baseCells": c["baseCells"],
                        "foldArrows": c["foldArrows"],
                        "nH": c.get("nH"), "nV": c.get("nV")} for c in s["chains"]],
            "verdict": s["verdict"],
            "twistEngines": s["twistEngines"],
            "canonicalHash": s.get("canonicalHash"),
        }
        fn = "%s_%d.json" % (grid, sid)
        with open(os.path.join(OUTDIR, fn), "w") as fh:
            json.dump(rec, fh, indent=2)
        manifest.append({"file": fn, "grid": grid, "id": sid, "K": K, "shape": shape,
                         "tier": meta["tier"], "class": meta["class"]})
        md.append("| %d | `%s#%d` | %d | %s | %s | %s | %s |"
                  % (i, grid, sid, K, shape, meta["class"], meta["FOLD_means"], meta["JAM_means"]))

    md.append("\n## Per-pattern fold sheets\n")
    for i, (grid, sid, meta) in enumerate(TO_FOLD, 1):
        s = index.get((grid, sid))
        if s is None:
            continue
        m, n = map(int, grid.split("x"))
        K = m * n // 3
        t = s["twistEngines"]
        md.append("### %d. `%s#%d`  (%s, %d×%d grid, K=%d)\n" %
                  (i, grid, sid, s["footprint"]["shape"], m, n, K))
        md.append("- **tier:** %s" % meta["tier"])
        md.append("- **class:** %s" % meta["class"])
        md.append("- **engine predicts:** %s" % meta["predicted"])
        md.append("- **footprint cells:** %s" %
                  " ".join("(%d,%d)" % (c["x"], c["y"]) for c in s["footprint"]["cells"]))
        md.append("- **chains (fold each in arrow order):**")
        md.append("```")
        md.extend(_chain_lines(s["chains"]))
        md.append("```")
        md.append("- **twist verdicts:** no=%s jump=%s normal=%s | partial=%s (Tw=%s)\n" %
                  (t["no decomp"]["tw"], t["jump decomp"]["tw"], t["normal decomp"]["tw"],
                   t["partial decomp"]["class"], t["partial decomp"]["tw"]))
        md.append("- **record:** [ ] FOLD  [ ] JAM  [ ] FOLD-with-overhang (one end sticks out)\n")

    with open(os.path.join(OUTDIR, "_manifest.json"), "w") as fh:
        json.dump({"set": manifest}, fh, indent=2)
    with open(os.path.join(OUTDIR, "_TEST_PLAN.md"), "w") as fh:
        fh.write("\n".join(md) + "\n")

    print("parked %d patterns -> %s" % (len(manifest), os.path.relpath(OUTDIR, ROOT)))
    for mf in manifest:
        print("  %-9s K=%-2d %-4s %s" % (mf["grid"] + "#" + str(mf["id"]), mf["K"], mf["shape"], mf["tier"]))


if __name__ == "__main__":
    main()
