"""test_manifest_counts.py — independent anchor: engine counts must equal committed manifest.

The golden files are generated FROM the engine, so test_golden.py alone is self-referential. A frozen
manifest + result files in square/tests/fixtures/ hold solution counts produced by EARLIER, separately-dated
engine runs; asserting the current engine reproduces them is the one cross-check not generated by this
suite. The corpus lives under square/tests/fixtures/ (NOT the live results/, which is regenerable and gets
wiped) so the anchor is permanent. Current committed baseline (the curated fixture set):
6x4→6, 6x5→11 (3-stack, corner-only; reset 2026-07-18 when parity was demoted to a diagnostic —
was 2/3 under the old parity filter); 6x4→15, 6x5→44 (2-stack, parity-independent, unchanged).
"""
from __future__ import annotations

import json
import os
from typing import Any

import pytest

import enginelib as EL  # noqa: E402  (sys.path set in conftest.py)

# Grids whose engine re-run is expensive — assert under `-m slow` only (same set as test_golden).
SLOW_GRIDS: set[tuple[int, int]] = {(6, 6), (6, 7), (9, 4), (8, 6), (12, 4)}

_HERE: str = os.path.dirname(os.path.abspath(__file__))
_RESULTS: str = os.path.join(_HERE, "fixtures")   # frozen anchor corpus, independent of live results/


def _live_entries() -> list[dict[str, Any]]:
    """Manifest entries whose result file still exists. I/O: () -> list of manifest entry dicts."""
    path = os.path.join(_RESULTS, "manifest.json")
    if not os.path.exists(path):
        return []
    with open(path) as f:
        entries = json.load(f)
    return [e for e in entries if os.path.exists(os.path.join(_RESULTS, e["file"]))]


def _params(stacks: int) -> list[Any]:
    """pytest params for live manifest entries with the given stack count (3-stack nc=False only).
    I/O: (stacks) -> list[pytest.param], slow-marked by grid; one skip param if none found."""
    out: list[Any] = []
    for e in _live_entries():
        opts = e["opts"]
        if opts.get("stacks", 3) != stacks:
            continue
        if stacks == 3 and opts.get("allowNonCorner"):
            continue  # manifest baseline is corner-only
        if opts.get("storeAll"):
            continue  # store-all entries hold the COVERED set (gates annotate, never prune) — its count
            # is not the gated-engine baseline this test anchors on (e.g. 3x2 store-all=4 vs gated=2)
        marks = [pytest.mark.slow] if (e["m"], e["n"]) in SLOW_GRIDS else []
        out.append(pytest.param(e, id=f"{e['m']}x{e['n']}:{e['key']}", marks=marks))
    return out or [pytest.param(None, id=f"no-manifest-stacks{stacks}")]


@pytest.mark.parametrize("entry", _params(3))
def test_3stack_count_matches_manifest(entry: dict[str, Any] | None) -> None:
    """Current 3-stack engine count must equal the committed manifest count for the entry.
    I/O: (manifest entry | None) -> None (asserts count)."""
    if entry is None:
        pytest.skip("no live 3-stack manifest entries")
    solutions, _ctx = EL.run_3stack(entry["m"], entry["n"], allow_non_corner=False)
    assert len(solutions) == entry["count"], (
        f"{entry['m']}x{entry['n']}: engine {len(solutions)} != manifest {entry['count']} "
        f"({entry['file']})")


@pytest.mark.parametrize("entry", _params(2))
def test_2stack_count_matches_manifest(entry: dict[str, Any] | None) -> None:
    """Current 2-stack engine count must equal the committed manifest count for the entry.
    I/O: (manifest entry | None) -> None (asserts count)."""
    if entry is None:
        pytest.skip("no live 2-stack manifest entries")
    solutions, _ctx = EL.run_2stack(entry["m"], entry["n"])
    assert len(solutions) == entry["count"], (
        f"{entry['m']}x{entry['n']}: engine {len(solutions)} != manifest {entry['count']} "
        f"({entry['file']})")
